In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('data/Churn_Modelling.csv')
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [6]:
df.describe().round(2)

RowNumber   CustomerId  CreditScore       Age    Tenure    Balance  \
count   10000.00     10000.00     10000.00  10000.00  10000.00   10000.00   
mean     5000.50  15690940.57       650.53     38.92      5.01   76485.89   
std      2886.90     71936.19        96.65     10.49      2.89   62397.41   
min         1.00  15565701.00       350.00     18.00      0.00       0.00   
25%      2500.75  15628528.25       584.00     32.00      3.00       0.00   
50%      5000.50  15690738.00       652.00     37.00      5.00   97198.54   
75%      7500.25  15753233.75       718.00     44.00      7.00  127644.24   
max     10000.00  15815690.00       850.00     92.00     10.00  250898.09   

       NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary   Exited  
count       10000.00   10000.00        10000.00         10000.00  10000.0  
mean            1.53       0.71            0.52        100090.24      0.2  
std             0.58       0.46            0.50         57510.49      0.4  
min             1.00       0.00            0.00            11.58      0.0  
25%             1.00       0.00            0.00         51002.11      0.0  
50%             1.00       1.00            1.00        100193.92      0.0  
75%             2.00       1.00            1.00        149388.25      0.0  
max             4.00       1.00            1.00        199992.48      1.0

### Normalization

In [10]:
new_df = pd.DataFrame(df, columns=['Age', 'Tenure'])
new_df.head()

Age  Tenure
0   42       2
1   41       1
2   42       8
3   39       1
4   43       2

In [11]:
new_df.isnull().sum()

Age       0
Tenure    0
dtype: int64

In [12]:
scaler = MinMaxScaler()
normalize_df = scaler.fit_transform(new_df)
normalize_df

array([[0.32432432, 0.2       ],
       [0.31081081, 0.1       ],
       [0.32432432, 0.8       ],
       ...,
       [0.24324324, 0.7       ],
       [0.32432432, 0.3       ],
       [0.13513514, 0.4       ]])

In [13]:
x_array = np.array([[2],[3],[5],[6],[6]])

scaler = MinMaxScaler()
norm_df =scaler.fit_transform(x_array)
norm_df

array([[0.  ],
       [0.25],
       [0.75],
       [1.  ],
       [1.  ]])

### Standardization

In [14]:
scaler = StandardScaler()
std_df = scaler.fit_transform(new_df)
std_df

array([[ 0.29351742, -1.04175968],
       [ 0.19816383, -1.38753759],
       [ 0.29351742,  1.03290776],
       ...,
       [-0.27860412,  0.68712986],
       [ 0.29351742, -0.69598177],
       [-1.04143285, -0.35020386]])

In [15]:
x_array = np.array([[2],[3],[5],[6],[6]])

scaler = StandardScaler()
std_df =scaler.fit_transform(x_array)
std_df

array([[-1.47709789],
       [-0.86164044],
       [ 0.36927447],
       [ 0.98473193],
       [ 0.98473193]])